export {default as Dashboard} from './Dashboard'
export {default as  ClaimSubmission} from './ClaimSubmission'
export {default as Allvehicle } from './AllVehicle'
export {default as AllClaims } from './AllClaims'
export {default as Policies } from './Policies'
export {default as InsurancePolicyRegister} from './InsurancePolicy'
export {default as VehicleRegisteration} from '../components/VehicleRegisteration'